### ISSUE TITLE
Too many parallel processes are used

### ISSUE THREAD

**Issue by MarcBHahn** [BAMresearch/McSAS3#5]
When running a simulation with for example 50 repetitions, 50 parallel processes are started which is a little too much on a standard workstation. There seems to be a check in the source which isn't currently working properly.

**Comment by MarcBHahn** [comment]
I found the problem and fixed it. Gonna generate a PR

**Comment by toqduj** [comment]
There should be a limit in the code, which limits the number of simultaneous threads to no more than the number of cores available. It shouldn't start 50 if you only have 12 cores available. Does this not function properly?

**Comment by MarcBHahn** [comment]
No that didnt work properly. But I found the error and fixed it. Its in my "threads-option" branch, I will create a PR so you can have a look at the fix and the additional option implemented.

**Comment by toqduj** [comment]
Is this still an issue?
